### PR TITLE
add common function to append stripe field

### PR DESCRIPTION
**Pull request by ccarruitero**
Move common append functionality to a function

### CODE REVIEW

**Comment by ccarruitero** [comment]
Failed builds in master was becauser `ffaker` problem. Now that is solved that problem should be ok.
@tvdeyen Can you run the build again?

**Comment by tvdeyen** [comment]
You need to rebase with latest master (and force push) otherwise a rebuild would fail again.

**Comment by ccarruitero** [comment]
@tvdeyen I updated the branch, but seem to be appears an error in other build. I was making tests in local, but I couldn't replicate the error.

I saw similar errors in other pull requests and I think is something related with the external request that we do.

**Comment by ccarruitero** [comment]
Is just a code improvement. The change only avoid repeting code for append the fields.

**Comment by tvdeyen** [comment]
As noted on #71 we will stop adding new features or changes into this gem as we want to encourage people to use individual extensions for payment providers instead.

So, please understand that I will reject this change here now.

Thanks for all your contributions lately. This is very much appreciated!

**Pull request closed without merging**
